ReserveProxy:
  Routes:
    UserService:
      ClusterId: UserService
      Match:
        Path: "/user-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /user-api
        - PathPrefix: /api
    ProductService:
      ClusterId: ProductService
      Match:
        Path: "/product-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /product-api
        - PathPrefix: /api
    BasketService:
      ClusterId: BasketService
      Match:
        Path: "/basket-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /basket-api
        - PathPrefix: /api
    OrderService:
      ClusterId: OrderService
      Match:
        Path: "/order-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /order-api
        - PathPrefix: /api
  Clusters:
    UserService:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true
      LoadBalancingPolicy": RoundRobin
      Destinations:
        UserService-2:
          Address: https://user-api:443
          # Address: https://localhost:7100
    ProductService:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true
      LoadBalancingPolicy": RoundRobin
      Destinations:
        ProductService-2:
          # Address: https://localhost:7295
          Address: https://product-api:443
    BasketService:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true
      LoadBalancingPolicy": RoundRobin
      Destinations:
        BasketService-2:
          # Address: https://localhost:7024
          Address: https://basket-api:443
    OrderService:
      HttpClient:
        DangerousAcceptAnyServerCertificate: true
      LoadBalancingPolicy": RoundRobin
      Destinations:
        OrderService-2:
          # Address: https://localhost:7003
          Address: https://order-api:443