ReserveProxy:
  Routes:
    UserService:
      ClusterId: UserService
      Match:
        Path: "/user-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /user-api
        - PathPrefix: /api
    ProductService:
      ClusterId: ProductService
      Match:
        Path: "/product-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /product-api
        - PathPrefix: /api
    BasketService:
      ClusterId: BasketService
      Match:
        Path: "/basket-api/{**catch-all}"
      Transforms:
        - PathRemovePrefix: /basket-api
        - PathPrefix: /api
  Clusters:
    UserService:
      Destinations:
        UserService-1:
          Address: https://localhost:7100
        UserService-2:
          Address: http://localhost:5236
    ProductService:
      Destinations:
        ProductService-1:
          Address: https://localhost:7295
        ProductService-2:
          Address: http://localhost:5138
    BasketService:
      Destinations:
        BasketService-1:
          Address: https://localhost:7024
        BasketService-2:
          Address: http://localhost:5188